#!/usr/bin/env python3
"""Generate src/images.h with the 1-bit bitmaps (128x64) used by the firmware.

Each image comes from a PNG in the project directory (ideal aspect ratio 2:1):
    splash.png, warning.png, panic.png
Pipeline: grayscale -> resize (LANCZOS) -> 1-bit (Floyd-Steinberg dithering).
To change an image, replace the PNG and run this script again.
"""
from PIL import Image

W, H = 128, 64
BASE = "/home/lemes-eulen/esp32/server-display"
OUT_H = BASE + "/src/images.h"
NAMES = ["splash", "warning", "panic"]


def to_xbm_bytes(img1):
    """PIL mode '1' -> XBM bytes (LSB-first); bit=1 => pixel ON (white)."""
    px = img1.load()
    rb = (W + 7) // 8
    data = bytearray(rb * H)
    for y in range(H):
        for x in range(W):
            if px[x, y] != 0:
                data[y * rb + (x >> 3)] |= (1 << (x & 7))
    return data


def load(name):
    return (Image.open("%s/%s.png" % (BASE, name))
            .convert("L").resize((W, H), Image.LANCZOS).convert("1"))


IMAGES = [(n, load(n)) for n in NAMES]

# stacked preview (5x) for inspection
prev = Image.new("L", (W * 5, H * 5 * len(IMAGES)), 0)
for i, (_, im) in enumerate(IMAGES):
    prev.paste(im.convert("L").resize((W * 5, H * 5), Image.NEAREST), (0, i * H * 5))
prev.save("/tmp/images_preview.png")

with open(OUT_H, "w") as f:
    f.write("#pragma once\n// Generated by tools/gen_images.py\n")
    f.write("#define IMG_W %d\n#define IMG_H %d\n\n" % (W, H))
    for name, im in IMAGES:
        data = to_xbm_bytes(im)
        f.write("static const unsigned char img_%s[] = {\n" % name)
        for i in range(0, len(data), 16):
            f.write("  " + ", ".join("0x%02x" % b for b in data[i:i + 16]) + ",\n")
        f.write("};\n\n")

print("OK -> %s  | preview -> /tmp/images_preview.png" % OUT_H)
